{
 "title": "Nvidia",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repo",
    "label": "Repository",
    "query": "SELECT repo_name FROM commit_details\nUNION\nSELECT repo_name FROM pr_details\nUNION\nSELECT repo_name FROM lead_time_to_change\nUNION\nSELECT repo_name FROM incidents_for_mttr\nUNION\nSELECT repo_name FROM change_failure_rate_runs\nUNION\nSELECT repo_name FROM build_durations\nORDER BY repo_name"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style='width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;'><h1 style='margin: 0; font-size: 3em; font-weight: 500;'>DevSecOps1.0</h1></div>"
   }
  },
  {
   "title": "Development Metrics Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Commits",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(*) FROM commit_details WHERE $__timeFilter(commit_date) AND repo_name IN (${repo:sqlstring})"
      }
     ]
    },
    {
     "title": "No of Developers",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(distinct commit_user) from commit_details WHERE $__timeFilter(commit_date) AND repo_name IN (${repo:sqlstring})"
      }
     ]
    },
    {
     "title": "Lines Changed ",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select sum(additions+deletions) as lines_changed  from commit_details WHERE $__timeFilter(commit_date) AND repo_name IN (${repo:sqlstring})"
      }
     ]
    },
    {
     "title": "Files Changed ",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select sum(files_changed)  from commit_details WHERE $__timeFilter(commit_date) AND repo_name IN (${repo:sqlstring})"
      }
     ]
    },
    {
     "title": "PRs",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(*) from pr_details WHERE $__timeFilter(start_date) AND repo_name IN (${repo:sqlstring})"
      }
     ]
    },
    {
     "title": "PR Status - Closed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select count(state) state from pr_details  WHERE state='closed' AND $__timeFilter(start_date) AND repo_name IN (${repo:sqlstring})"
      }
     ]
    }
   ]
  },
  {
   "title": "SonarQube Quality Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Coverage Trend",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT analysis_date AS \"time\", coverage FROM sonarqube_results WHERE $__timeFilter(analysis_date) ORDER BY analysis_date"
      }
     ]
    },
    {
     "title": "Bugs Trend",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT analysis_date AS \"time\", bugs FROM sonarqube_results WHERE $__timeFilter(analysis_date) ORDER BY analysis_date"
      }
     ]
    },
    {
     "title": "Vulnerabilities Trend",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT analysis_date AS \"time\", vulnerabilities FROM sonarqube_results WHERE $__timeFilter(analysis_date) ORDER BY analysis_date"
      }
     ]
    },
    {
     "title": "Code Smells Trend",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT analysis_date AS \"time\", code_smells FROM sonarqube_results WHERE $__timeFilter(analysis_date) ORDER BY analysis_date"
      }
     ]
    },
    {
     "title": "Quality Gate Status",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT quality_gate_status, COUNT(*) FROM sonarqube_results WHERE $__timeFilter(analysis_date) GROUP BY quality_gate_status"
      }
     ]
    },
    {
     "title": "Reliability Rating",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 8, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT AVG(reliability_rating) FROM sonarqube_results WHERE $__timeFilter(analysis_date)"
      }
     ]
    },
    {
     "title": "Security Rating",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 13, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT AVG(security_rating) FROM sonarqube_results WHERE $__timeFilter(analysis_date)"
      }
     ]
    },
    {
     "title": "Maintainability Rating",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 18, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT AVG(maintainability_rating) FROM sonarqube_results WHERE $__timeFilter(analysis_date)"
      }
     ]
    },
    {
     "title": "Quality Gate SLO Compliance",
     "type": "gauge",
     "description": "SLI: % builds passing Quality Gate. SLO: >=95% green, >=80% orange, <80% red.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) FILTER (WHERE quality_gate_status = 'OK') * 100.0 / COUNT(*) AS pass_rate FROM sonarqube_results WHERE $__timeFilter(analysis_date)"
      }
     ]
    }
   ]
  },
  {
   "title": "Development Metrics Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lead Time to Change by Repository",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "targets": [
      {
       "rawSql": "SELECT\n  repo_name AS \"Repository\",\n  AVG(lead_time_in_seconds) / 3600 AS \"Average Lead Time (Hours)\"\nFROM\n  lead_time_to_change\nWHERE\n  $__timeFilter(merged_at) AND\n  repo_name IN (${repo:sqlstring})\nGROUP BY\n  repo_name\nORDER BY\n  \"Average Lead Time (Hours)\" DESC"
      }
     ]
    },
    {
     "title": "Commits per Developer",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "rawSql": "SELECT commit_user, count(*) FROM commit_details WHERE $__timeFilter(commit_date) AND repo_name IN (${repo:sqlstring}) group by commit_user"
      }
     ]
    },
    {
     "title": "Files Changed per Developer",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "targets": [
      {
       "rawSql": "select commit_user, sum(files_changed)  from commit_details WHERE $__timeFilter(commit_date) AND repo_name IN (${repo:sqlstring}) group by commit_user"
      }
     ]
    },
    {
     "title": "Lines Changed per Developer",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "targets": [
      {
       "rawSql": "select commit_user, sum(additions+deletions) as lines_changed  from commit_details  WHERE $__timeFilter(commit_date) AND repo_name IN (${repo:sqlstring}) group by commit_user"
      }
     ]
    },
    {
     "title": "Merge Frequency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('day', end_date) AS \"time\",\n  repo_name,\n  COUNT(*) AS \"Merges\"\nFROM \n  public.pr_details\nWHERE \n  $__timeFilter(end_date)\n  AND merged = true\n  AND repo_name IN (${repo:sqlstring}) \nGROUP BY \n  \"time\", repo_name\nORDER BY \n  \"time\" ASC;"
      }
     ]
    },
    {
     "title": "Commits per day",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('day', commit_date) AS \"time\",\n  repo_name,\n  COUNT(*) AS \"Commits\"\nFROM \n  commit_details\nWHERE\n  $__timeFilter(commit_date) AND\n  repo_name IN (${repo:sqlstring})\nGROUP BY \n  \"time\", repo_name\nORDER BY \n  \"time\" ASC;"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipeline Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pipeline Frequency",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "rawSql": "SELECT\n  date_trunc('day', completed_at) AS \"time\",\n  repo_name,\n  COUNT(*) AS \"Builds\"\nFROM \n  change_failure_rate_runs\nWHERE\n  $__timeFilter(completed_at) AND\n  repo_name IN (${repo:sqlstring})\nGROUP BY \n  \"time\", repo_name\nORDER BY \n  \"time\" ASC;"
      }
     ]
    },
    {
     "title": "Total Releases",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) FROM change_failure_rate_runs\nWHERE $__timeFilter(completed_at) AND repo_name IN (${repo:sqlstring})"
      }
     ]
    },
    {
     "title": "Successful Releases",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) FROM change_failure_rate_runs\nWHERE $__timeFilter(completed_at) AND repo_name IN (${repo:sqlstring}) AND conclusion = 'success'"
      }
     ]
    },
    {
     "title": "Average Release Duration (Mins)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT AVG(duration_in_seconds) / 60 FROM build_durations\nWHERE $__timeFilter(completed_at) AND repo_name IN (${repo:sqlstring})"
      }
     ]
    },
    {
     "title": "Nightly Pipeline Runs Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT repo_name AS pipeline_name, completed_at, conclusion AS status, failure_reason FROM change_failure_rate_runs WHERE $__timeFilter(completed_at) ORDER BY completed_at DESC"
      }
     ]
    },
    {
     "title": "Failed Releases with Failure Reasons",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "rawSql": "SELECT completed_at, repo_name, failure_reason FROM change_failure_rate_runs WHERE $__timeFilter(completed_at) AND repo_name IN (${repo:sqlstring}) AND conclusion = 'failure' ORDER BY completed_at DESC"
      }
     ]
    }
   ]
  },
  {
   "title": "DORA Metrics Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Change Failure Rate Score",
     "type": "gauge",
     "description": "<table style=\"border: 1px solid #ccc; border-collapse: collapse;\">\n  <thead>\n    <tr>\n      <th style=\"border: 1px solid #ccc; padding: 8px; text-align: left;\">Value</th>\n      <th style=\"border: 1px solid #ccc; padding: 8px; text-align: left;\">Score</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">&lt;1 hour</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">0-17</td>\n    </tr>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">&lt;1 day</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">18-34</td>\n    </tr>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">1 day - 1 week</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">35-51</td>\n    </tr>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">1 week - 1 month</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">52-67</td>\n    </tr>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">1 month - 6 months</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">68-84</td>\n    </tr>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">&gt; 6 months</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">85-100</td>\n    </tr>\n  </tbody>\n</table>",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 106 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "WITH metric AS (\n  SELECT COALESCE(CAST(COUNT(CASE WHEN conclusion = 'failure' THEN 1 END) AS REAL) * 100 / NULLIF(COUNT(*), 0), 0) as value FROM change_failure_rate_runs WHERE $__timeFilter(completed_at) AND repo_name IN (${repo:sqlstring})\n)\nSELECT CASE WHEN value <= 15 THEN 10 WHEN value <= 30 THEN 8 WHEN value <= 45 THEN 5 ELSE 2 END\nFROM metric"
      }
     ]
    },
    {
     "title": "Overall Avg Lead Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  AVG(lead_time_in_seconds) / 3600\nFROM \n  lead_time_to_change\nWHERE\n  $__timeFilter(merged_at) AND\n  repo_name IN (${repo:sqlstring})"
      }
     ]
    },
    {
     "title": "Deployment Frequency (per month)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 124 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COALESCE((CAST(COUNT(*) AS REAL) / NULLIF(EXTRACT(DAYS FROM (MAX(completed_at) - MIN(completed_at))), 0)) * 30.44, 0) FROM change_failure_rate_runs WHERE $__timeFilter(completed_at) AND repo_name IN (${repo:sqlstring}) AND conclusion = 'success'"
      }
     ]
    },
    {
     "title": "Change Failure Rate",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  CAST(COUNT(CASE WHEN conclusion = 'failure' THEN 1 END) AS REAL) * 100 / NULLIF(COUNT(*), 0)\nFROM\n  change_failure_rate_runs\nWHERE\n  $__timeFilter(completed_at) AND repo_name IN (${repo:sqlstring})"
      }
     ]
    },
    {
     "title": "Mean Time to Recovery (Hours)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  AVG(time_to_recover_in_seconds) / 3600\nFROM\n  incidents_for_mttr\nWHERE\n  $__timeFilter(resolution_time) AND repo_name IN (${repo:sqlstring})"
      }
     ]
    },
    {
     "title": "Lead Time Score",
     "type": "gauge",
     "description": "<table style=\"width:100%\">\n  <tr>\n    <th>Value (Range)</th>\n    <th>Score</th>\n  </tr>\n  <tr>\n    <td>&lt; 1 hour</td>\n    <td>9-10</td>\n  </tr>\n  <tr>\n    <td>&lt; 1 day</td>\n    <td>7-8</td>\n  </tr>\n  <tr>\n    <td>1 day - 1 week</td>\n    <td>5-6</td>\n  </tr>\n  <tr>\n    <td>1 week - 1 month</td>\n    <td>3-4</td>\n  </tr>\n  <tr>\n    <td>1 month - 6 months</td>\n    <td>1-2</td>\n  </tr>\n  <tr>\n    <td>&gt; 6 months</td>\n    <td>0</td>\n  </tr>\n</table>",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 128 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "WITH metric AS (\n  SELECT COALESCE(AVG(lead_time_in_seconds) / 3600, 99999) as value FROM lead_time_to_change WHERE $__timeFilter(merged_at) AND repo_name IN (${repo:sqlstring})\n)\nSELECT CASE \n  WHEN value <= 1 THEN 10\n  WHEN value <= 24 THEN 8\n  WHEN value <= 168 THEN 6\n  WHEN value <= 720 THEN 4\n  WHEN value <= 4380 THEN 2\n  ELSE 0 \nEND\nFROM metric"
      }
     ]
    },
    {
     "title": "Deploy Frequency Score",
     "type": "gauge",
     "description": "<table style=\"border: 1px solid #ccc; border-collapse: collapse;\">\n  <thead>\n    <tr>\n      <th style=\"border: 1px solid #ccc; padding: 8px; text-align: left;\">Value</th>\n      <th style=\"border: 1px solid #ccc; padding: 8px; text-align: left;\">Score</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">On Demand</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">9-10</td>\n    </tr>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">1 hour - 1 day</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">7-8</td>\n    </tr>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">1 day - 1 week</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">5-6</td>\n    </tr>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">1 week - 1 month</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">3-4</td>\n    </tr>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">1 month - 6 months</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">1-2</td>\n    </tr>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">&gt; 6 months</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">0</td>\n    </tr>\n  </tbody>\n</table>",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 128 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "WITH metric AS (\n  SELECT COALESCE(CAST(COUNT(*) AS REAL) / NULLIF(EXTRACT(DAYS FROM (MAX(completed_at) - MIN(completed_at))), 0), 0) as value FROM change_failure_rate_runs WHERE $__timeFilter(completed_at) AND repo_name IN (${repo:sqlstring}) AND conclusion = 'success'\n)\nSELECT CASE WHEN value >= 1 THEN 10 WHEN value >= 0.14 THEN 8 WHEN value > 0.033 THEN 5 ELSE 2 END\nFROM metric"
      }
     ]
    },
    {
     "title": "MTTR Score",
     "type": "gauge",
     "description": "<table style=\"border: 1px solid #ccc; border-collapse: collapse;\">\n  <thead>\n    <tr>\n      <th style=\"border: 1px solid #ccc; padding: 8px; text-align: left;\">Value</th>\n      <th style=\"border: 1px solid #ccc; padding: 8px; text-align: left;\">Score</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">&lt;1 hour</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">9-10</td>\n    </tr>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">&lt;1 day</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">7-8</td>\n    </tr>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">1 day - 1 week</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">5-6</td>\n    </tr>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">1 week - 1 month</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">3-4</td>\n    </tr>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">1 month - 6 months</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">1-2</td>\n    </tr>\n    <tr>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">&gt; 6 months</td>\n      <td style=\"border: 1px solid #ccc; padding: 8px;\">0</td>\n    </tr>\n  </tbody>\n</table>",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 128 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "WITH metric AS (\n  SELECT COALESCE(AVG(time_to_recover_in_seconds) / 3600, 0) as value FROM incidents_for_mttr WHERE $__timeFilter(resolution_time) AND repo_name IN (${repo:sqlstring})\n)\nSELECT CASE WHEN value <= 1 THEN 10 WHEN value <= 24 THEN 8 WHEN value <= 168 THEN 5 ELSE 2 END\nFROM metric"
      }
     ]
    }
   ]
  },
  {
   "title": "DORA Performance Score",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Delivery Performance",
     "type": "stat",
     "description": "Benchmarking<br>Elite - If score is >8-10 <br>High - If score is >6-8 <br> Medium - If score is >4-6 <br> Low - If score is below 4",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "WITH\nlead_time AS (\n  SELECT COALESCE(AVG(lead_time_in_seconds) / 3600, 8000) as value FROM lead_time_to_change WHERE $__timeFilter(merged_at) AND repo_name IN (${repo:sqlstring})\n),\ndeploy_freq AS (\n  SELECT COALESCE(CAST(COUNT(*) AS REAL) / NULLIF(EXTRACT(DAYS FROM (MAX(completed_at) - MIN(completed_at))), 0), 0) as value FROM change_failure_rate_runs WHERE $__timeFilter(completed_at) AND repo_name IN (${repo:sqlstring}) AND conclusion = 'success'\n),\nchange_fail_rate AS (\n  SELECT COALESCE(CAST(COUNT(CASE WHEN conclusion = 'failure' THEN 1 END) AS REAL) * 100 / NULLIF(COUNT(*), 0), 0) as value FROM change_failure_rate_runs WHERE $__timeFilter(completed_at) AND repo_name IN (${repo:sqlstring})\n),\nmttr AS (\n  SELECT COALESCE(AVG(time_to_recover_in_seconds) / 3600, 0) as value FROM incidents_for_mttr WHERE $__timeFilter(resolution_time) AND repo_name IN (${repo:sqlstring})\n),\nscores AS (\n  SELECT\n    (CASE WHEN lt.value <= 24 THEN 10 WHEN lt.value <= 168 THEN 8 WHEN lt.value <= 720 THEN 5 ELSE 2 END) as lt_score,\n    (CASE WHEN df.value >= 1 THEN 10 WHEN df.value >= 0.14 THEN 8 WHEN df.value > 0.033 THEN 5 ELSE 2 END) as df_score,\n    (CASE WHEN cfr.value <= 15 THEN 10 WHEN cfr.value <= 30 THEN 8 WHEN cfr.value <= 45 THEN 5 ELSE 2 END) as cfr_score,\n    (CASE WHEN m.value <= 1 THEN 10 WHEN m.value <= 24 THEN 8 WHEN m.value <= 168 THEN 5 ELSE 2 END) as mttr_score\n  FROM lead_time lt, deploy_freq df, change_fail_rate cfr, mttr m\n),\nfinal_score AS (\n  SELECT (lt_score + df_score + cfr_score + mttr_score) / 4.0 as score\n  FROM scores\n)\nSELECT\n  score as \"Score (1-10)\",\n  CASE\n    WHEN score >= 9 THEN 4\n    WHEN score >= 7 THEN 3\n    WHEN score >= 4 THEN 2\n    ELSE 1\n  END as \"Rating\"\nFROM final_score"
      }
     ]
    }
   ]
  }
 ]
}